### PR TITLE
Sloth nasty 6000

### PR DESCRIPTION
**Pull request by pirog**

### CODE REVIEW

**Comment by donkoller** [comment]
Mike, do you anticipate a first useful release of Kalabox 2 in January?
 	
Don Koller 
BEA Enterprises, Inc.
17 Lake Potomac Ct. | Potomac, MD 20854 USA
office: 301-299-7900 | mobile 301-520-9820

web: bea-enterprises.com <http://bea-enterprises.com/> | email: don@bea-enterprises.com <mailto:don@bea-enterprises.com>

**Comment by pirog** [comment]
@donkoller we are planning for a soft launch at SANDCAMP in late February. 

In terms of a "useful" release... what sort of functionality would you need to make it "useful"? :)

**Comment by donkoller** [comment]
Mike,
Sorry for my meaningless ref to “useful."

When I try to git clone git@github.com:kalabox/kalabox.git
the response is:  
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
I thought the repo was public. What am I doing wrong?

Don
 	
Don Koller 
BEA Enterprises, Inc.
17 Lake Potomac Ct. | Potomac, MD 20854 USA
office: 301-299-7900 | mobile 301-520-9820

web: bea-enterprises.com <http://bea-enterprises.com/> | email: don@bea-enterprises.com <mailto:don@bea-enterprises.com>

**Comment by pirog** [comment]
It is but i *think* you need to use the "https" version of the git repo:
https://github.com/kalabox/kalabox.git. Let me know if that works for you.

On Sat, Jan 3, 2015 at 9:53 AM, Don Koller <notifications@github.com> wrote:

> Mike,
> Sorry for my meaningless ref to “useful."
>
> When I try to git clone git@github.com:kalabox/kalabox.git
> the response is:
> Permission denied (publickey).
> fatal: Could not read from remote repository.
> Please make sure you have the correct access rights
> and the repository exists.
> I thought the repo was public. What am I doing wrong?
>
> Don
>
> Don Koller
> BEA Enterprises, Inc.
> 17 Lake Potomac Ct. | Potomac, MD 20854 USA
> office: 301-299-7900 | mobile 301-520-9820
>
> web: bea-enterprises.com <http://bea-enterprises.com/> | email:
> don@bea-enterprises.com <mailto:don@bea-enterprises.com>
> > On Jan 2, 2015, at 10:15 PM, Mike Pirog <notifications@github.com>
> wrote:
> >
> > @donkoller <https://github.com/donkoller> we are planning for a soft
> launch at SANDCAMP in late February.
> >
> > In terms of a "useful" release... what sort of functionality would you
> need to make it "useful"? :)
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/kalabox/kalabox/pull/57#issuecomment-68581235>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox/pull/57#issuecomment-68603187>.
>



-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by pirog** [comment]
It is but i *think* you need to use the "https" version of the git repo:
https://github.com/kalabox/kalabox.git. Let me know if that works for you.

**Comment by donkoller** [comment]
I was already working in https://… Needed to cd to local directory from kalabox-master download.

STEP [13] -- Finishing up....
 - Installation complete!
Dons-MacBook-Pro-6:bin donkoller3$ kbox status
running
Dons-MacBook-Pro-6:bin donkoller3$ 


Thanks,
Don

**Pull request merged**
