### PR TITLE
Bugfix 390 syncthing bog down

### PR DESCRIPTION
**Pull request by pirog**

### CODE REVIEW

**Comment by pi-ron** [comment]
Hey Mike,  I was over on my colleagues machine and noticed her kbox sites were really slow.  I checked out activity monitor and syncthing was using a ton of cpu.  Is this what this issue is about?

She was running 0.9.18

I'm not sure how to check what version the git repo is up to now the branches / structure have changed.

**Comment by pirog** [comment]
It might be!

This fix will be in the 0.10.x we release. 

Can you tell us anything more about her setup aka how many apps she has running/installed, how much RAM her computer has, etc?

**Comment by ivyguo518** [comment]
Hello,
I have installed 5 apps,they are all Drupal websites pulled from pantheon, I usually only run one of them at the same time. I got 12 gb RAM installed, my computer is a iMac with 2.66 GHZ CPU running Yosemite.

**Comment by ivyguo518** [comment]
I've reduced my virtual machine base memory from 4 gb to 2 gb which saved me some RAM, I don't know if 4GB is necessary for kalabox? It seems 2 gb is running well for my apps at the moment.

**Comment by pirog** [comment]
Awesome! That is good to know. We've def heard other comments similar to this.

Maybe you all can comment on https://github.com/kalabox/kalabox/issues/459 so we can get momentum on that issue for the next release.

**Pull request merged**
