### PR TITLE
Update backends to get new B2D1.6

### PR DESCRIPTION
**Pull request by pirog**

### CODE REVIEW

**Comment by donkoller** [comment]
Mike, what happened to the online demo today? Never received a link or any notice.
Don

**Comment by pirog** [comment]
There was not a demo today. 

We are working to resolve the final issues of 0.7.0 before we do the demo:
https://github.com/kalabox/kalabox-issues/issues?q=is%3Aopen+is%3Aissue+label%3A0.7.0

**Comment by donkoller** [comment]
Thanks. Looks like good progress on CLI version. 
Don
 	
Don Koller 
BEA Enterprises, Inc.
17 Lake Potomac Ct. | Potomac, MD 20854 USA
office: 301-299-7900 | mobile 301-520-9820

web: bea-enterprises.com <http://bea-enterprises.com/> | email: don@bea-enterprises.com <mailto:don@bea-enterprises.com>

**Comment by pirog** [comment]
Yes. We are very excited about it! Things are coming together!

**Comment by donkoller** [comment]
See you at the con in LA.

**Pull request merged**
