### PR TITLE
Kalabox#237 Fix container names on uninstall / install for better err…

### PR DESCRIPTION
**Pull request by labboy0276**
…or reading

### CODE REVIEW

**Comment by reynoldsalec** [comment]
Looks like just a code style issue needs to get fixed here @labboy0276, otherwise this makes sense to me!

**Comment by labboy0276** [comment]
oops, i forgot to remove my testing stuff, oy vay

**Comment by labboy0276** [comment]
@reynoldsalec i fixeded the commit

**Comment by labboy0276** [comment]
This travis is failing cause the line is too long by 2 characters? sup with that?

**Pull request merged**
