### PR TITLE
#901: Use docker-compose compiled against older macs

### PR DESCRIPTION
**Pull request by pirog**

### CODE REVIEW

**Comment by hhcauldwell** [comment]
I reviewed this and it looks good, but wanted to understand it before I merge it in. Can you provide more details?

**Comment by pirog** [comment]
So this addressed #901 where the official docker-compose binary fails on older macs. I want to roll this in now so we can test the binary on newer mac architectures. 

I've used this binary to go through install and ive pulled a few sites down and it seems to work fine.

**Comment by pirog** [comment]
@rileysaurus

**Comment by hhcauldwell** [comment]
Thank you!

**Pull request merged**
